import { expect, testFactory } from './test'

const test = testFactory('custom-page')

test.describe('supports custom page sidebars', () => {
  test('updates a custom page sidebar', async ({ getPage }) => {
    const page = await getPage()
    await page.goTo('/custom/')

    const items = await page.getSidebarItems()

    expect(items).toMatchSidebar([
      { label: 'manual-a' },
      { label: 'custom' },
      { label: 'b' },
      { label: 'a' },
      { label: 'manual-b' },
    ])
  })

  test('only updates pagination links changed by autogenerated sidebar updates', async ({ getPage }) => {
    const page = await getPage()

    await page.expectPrevNextLinks('', [
      {
        url: '/manual-a/',
        expected: {
          prev: null,
          next: { href: '/custom-auto/b/', label: 'b' },
        },
      },
    ])
  })

  test('respects custom page pagination', async ({ getPage }) => {
    const page = await getPage()

    await page.expectPrevNextLinks('', [
      {
        url: '/custom/',
        expected: {
          prev: null,
          next: null,
        },
      },
    ])
  })
})
