import { expect, testFactory } from './test'

const test = testFactory('mixed')

test.describe('supports mixed sidebar autogenerated items', () => {
  test('updates root autogenerated entries', async ({ getPage }) => {
    const page = await getPage()
    await page.go()

    const items = await page.getSidebarItems()

    expect(items).toMatchSidebar([
      { label: 'Home' },
      { label: 'b' },
      { label: 'a' },
      {
        label: 'Mixed',
        items: [{ label: 'Manual Before' }, { label: 'b' }, { label: 'a' }, { label: 'Manual After' }],
      },
      {
        label: 'Adjacent',
        items: [{ label: 'b' }, { label: 'a' }, { label: 'a' }, { label: 'b' }],
      },
      { label: 'Last' },
    ])
  })

  test('preserves manual entries around autogenerated entries in a group', async ({ getPage }) => {
    const page = await getPage()
    await page.go()

    const items = await page.getSidebarGroupItems('Mixed')

    expect(items).toMatchSidebar([
      { label: 'Manual Before' },
      { label: 'b' },
      { label: 'a' },
      { label: 'Manual After' },
    ])
  })

  test('keeps adjacent autogenerated directories separate', async ({ getPage }) => {
    const page = await getPage()
    await page.go()

    const items = await page.getSidebarGroupItems('Adjacent')

    expect(items).toMatchSidebar([
      // `adjacent-a` is sorted by `reverse-slug`.
      { label: 'b' },
      { label: 'a' },
      // `adjacent-b` is sorted by `slug`.
      { label: 'a' },
      { label: 'b' },
    ])
  })
})

test.describe('updates prev/next links for mixed sidebar autogenerated items', () => {
  test('sets prev/next links for root autogenerated entries', async ({ getPage }) => {
    const page = await getPage()

    await page.expectPrevNextLinks('root-auto', [
      {
        url: '/b/',
        expected: {
          prev: { href: '/', label: 'Home' },
          next: { href: '/root-auto/a/', label: 'a' },
        },
      },
      {
        url: '/a/',
        expected: {
          prev: { href: '/root-auto/b/', label: 'b' },
          next: { href: '/manual-before/', label: 'Manual Before' },
        },
      },
    ])
  })

  test('sets prev/next links between manual and autogenerated entries in a group', async ({ getPage }) => {
    const page = await getPage()

    await page.expectPrevNextLinks('mixed-auto', [
      {
        url: '/b/',
        expected: {
          prev: { href: '/manual-before/', label: 'Manual Before' },
          next: { href: '/mixed-auto/a/', label: 'a' },
        },
      },
      {
        url: '/a/',
        expected: {
          prev: { href: '/mixed-auto/b/', label: 'b' },
          next: { href: '/manual-after/', label: 'Manual After' },
        },
      },
    ])
  })

  test('sets prev/next links for manual entries around autogenerated entries', async ({ getPage }) => {
    const page = await getPage()

    await page.expectPrevNextLinks('', [
      {
        url: '/manual-before/',
        expected: {
          prev: { href: '/root-auto/a/', label: 'a' },
          next: { href: '/mixed-auto/b/', label: 'b' },
        },
      },
      {
        url: '/manual-after/',
        expected: {
          prev: { href: '/mixed-auto/a/', label: 'a' },
          next: { href: '/adjacent-a/b/', label: 'b' },
        },
      },
    ])
  })

  test('sets prev/next links between adjacent autogenerated directories', async ({ getPage }) => {
    const page = await getPage()

    await page.expectPrevNextLinks('adjacent-a', [
      {
        url: '/b/',
        expected: {
          prev: { href: '/manual-after/', label: 'Manual After' },
          next: { href: '/adjacent-a/a/', label: 'a' },
        },
      },
      {
        url: '/a/',
        expected: {
          prev: { href: '/adjacent-a/b/', label: 'b' },
          next: { href: '/adjacent-b/a/', label: 'a' },
        },
      },
    ])

    await page.expectPrevNextLinks('adjacent-b', [
      {
        url: '/a/',
        expected: {
          prev: { href: '/adjacent-a/a/', label: 'a' },
          next: { href: '/adjacent-b/b/', label: 'b' },
        },
      },
      {
        url: '/b/',
        expected: {
          prev: { href: '/adjacent-b/a/', label: 'a' },
          next: { href: '/last/', label: 'Last' },
        },
      },
    ])
  })
})
