import { expect, testFactory } from './test'

const test = testFactory('no-sidebar')

test.describe('updates fallback autogenerated sidebar', () => {
  test('uses root metadata when no sidebar config is provided', async ({ getPage }) => {
    const page = await getPage()
    await page.go()

    const items = await page.getSidebarItems()

    expect(items).toMatchSidebar([
      {
        label: 'sub-1 (modified)',
        items: [{ label: 'sub-1/a' }, { label: 'sub-1/b' }],
      },
      { label: 'b' },
      { label: 'a' },
      { label: 'no-sidebar' },
    ])
  })

  test('updates nested directory metadata when no sidebar config is provided', async ({ getPage }) => {
    const page = await getPage()
    await page.go()

    const items = await page.getSidebarGroupItems('sub-1 (modified)')

    expect(items).toMatchSidebar([{ label: 'sub-1/a' }, { label: 'sub-1/b' }])
  })

  test('uses localized root metadata when no sidebar config is provided', async ({ getPage }) => {
    const page = await getPage()
    await page.goTo('/fr/')

    const items = await page.getSidebarItems()

    expect(items).toMatchSidebar([
      { label: 'no-sidebar-fr' },
      { label: 'a' },
      { label: 'b' },
      {
        label: 'sub-1 (modifié)',
        items: [{ label: 'sub-1/a' }, { label: 'sub-1/b' }],
      },
    ])
  })
})

test.describe('updates prev/next links for fallback autogenerated sidebar', () => {
  test('sets prev/next links using root metadata order', async ({ getPage }) => {
    const page = await getPage()

    await page.expectPrevNextLinks('sub-1', [
      {
        url: '/a/',
        expected: {
          // First sidebar item.
          prev: null,
          next: { href: '/sub-1/b/', label: 'sub-1/b' },
        },
      },
      {
        url: '/b/',
        expected: {
          prev: { href: '/sub-1/a/', label: 'sub-1/a' },
          next: { href: '/b/', label: 'b' },
        },
      },
    ])

    await page.expectPrevNextLinks('', [
      {
        url: '/b/',
        expected: {
          prev: { href: '/sub-1/b/', label: 'sub-1/b' },
          next: { href: '/a/', label: 'a' },
        },
      },
      {
        url: '/a/',
        expected: {
          prev: { href: '/b/', label: 'b' },
          next: { href: '/', label: 'no-sidebar' },
        },
      },
    ])
  })
})
